#ifndef ELOX_OPCODES_INLINE
typedef enum {
#define OPCODE(name) ADD_OP_##name,
#endif // ELOX_OPCODES_INLINE

OPCODE(UNDEFINED)
OPCODE(NUMBER_NUMBER)
OPCODE(STRING_STRING)

#ifndef ELOX_OPCODES_INLINE
#undef OPCODE
} OpCode;
#endif // ELOX_OPCODES_INLINE
