#ifndef ELOX_OPCODES_INLINE
typedef enum {
#define OPCODE(name) IN_OP_##name,
#endif // ELOX_OPCODES_INLINE

OPCODE(UNDEFINED)
OPCODE(STRING_STRING)
OPCODE(VALUE_ARRAY)

#ifndef ELOX_OPCODES_INLINE
#undef OPCODE
} OpCode;
#endif // ELOX_OPCODES_INLINE
